[package]
name = "syncaud"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
eframe = "0.29.1"
egui_extras = { version = "0.29.1", features = ["all_loaders"] }
rodio = "0.20.1"
serde = { version = "1.0.216", features = ["derive"] }

